######## USUARIOS #################
### Recuperar todas las usuarios
GET http://localhost:3000/users

### Recuperar usuario por username
GET http://localhost:3000/users?username=NARANDIA

### Esiste usuario por id o username
GET http://localhost:3000/users?username=NARANDIA

### Recuperar usuario por id
GET http://localhost:3000/users/3fbf28d7-c6e5-11ef-8b58-0a002700000b




### Crear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "daniel montoya",
  "username": "dmontoya",
  "password": "12345678"
}

### actualizar usuario
PATCH http://localhost:3000/users/6ecd7c4a-c90c-11ef-8b58-0a002700000b
Content-Type: application/json

{
  "username": "narandia",
  "passwrod": "12345678"
}

### Login usuario
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "dmontoya",
  "password": "12345678"
}


